version: '3'
services:
  pubnic-todo-dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: pubnic-todo-dynamodb
    ports:
        - "8000:8000"
    volumes:
        - "./.ignore/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    user: root
  pubnic-todo:
    build: .
    container_name: pubnic-todo
    depends_on:
        - pubnic-todo-dynamodb
    volumes:
      - .:/code
      - /code/.ignore/
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=DEVELOPMENT
      - AWS_ACCESS_KEY_ID=fake_access
      - AWS_SECRET_ACCESS_KEY=fake_secret
    #   - DOPPLER_TOKEN=<your-doppler-token>
